### ISSUE TITLE
axis config

### ISSUE THREAD

**Issue by team-ajas** [vostrenkov/FreeJoy#150]
Hello. I would like to know if it is possible to join two axes in one. But that only one of them works the prescale, because when joining them in equal mode the prescale varies the value of the two axes and not only the one assigned to the buttons for the regulation.
Thank you

**Comment by vostrenkov** [comment]
Can you please describe the behaviour that you need with examples?

**Comment by team-ajas** [comment]
Thank you in the end I have already achieved it greetings
