### ISSUE TITLE
bug report about shift registers V1.73

### ISSUE THREAD

**Issue by piogrammer** [vostrenkov/FreeJoy#151]
It is very convenient to use hc165 to expand the case. In order to reduce the delay, I tried to use multiple hc165 in parallel instead of chain transmission

When I use one alone, two in parallel,The program runs well

When three are connected in parallel, there is a certain probability of problems

But when i  tried to add 4 hc165 in parallel,pin map  shown in photo below
![1640914158(1)](https://user-images.githubusercontent.com/53431902/147797776-9ee74404-d6bc-4885-8c55-d39d21ddb9f6.jpg)
but they cant work 
and i found sothing wrong 
![F42K7 C{X8G(5Z4U(1HM H](https://user-images.githubusercontent.com/53431902/147797814-096354bf-979b-4c89-bd78-3aebaf873aa0.png)

as you can see 
all the latch pin are the same one（whitch i selected first）
i selected b12 b13 b14 b15 as Latch，then all the latch pin are B12
i selected b15 b14 b13 b12 as Latch，so  all the latch pin are B15
 sincerely hope that you can repair this fault as soon as possible.
love you dude

**Comment by Reksotiv** [comment]
I fixed this many months ago for version 1.7.1, but we delayed the release. This is an adapted version for 1.7.0, try it
[1.7.0.4-test.zip](https://github.com/FreeJoy-Team/FreeJoy/files/7795206/1.7.0.4-test.zip)

**Comment by piogrammer** [comment]
I think you can release the source code now,
It's exciting that this version of the register works normally.
thanks dude
