### ISSUE TITLE
Question regarding axis switching

### ISSUE THREAD

**Issue by wasyl00** [vostrenkov/FreeJoy#153]
I'm in the process of building farming sim controller. I would like to know if its possible to have one 2axis joystick but use it to control 4 axis with use of switch button between them. Basically switch in position A - joystick controls axis 1 and 2. Switch in position B joystick controls axis 3 and 4.  I'm considering hardware switching and software. I see multiple issues when trying to do it in hardware and I'm looking around for software options. Thanks

**Comment by vostrenkov** [comment]
What do you want to have on output of inactive axis?

**Comment by wasyl00** [comment]
Default positions for 2 innactive axis or even last values before the switch as I can always release joystick to conter itself before switching to other axis.

**Comment by vostrenkov** [comment]
You can use "Equal" function for axis activated by the button.
If you add auxiliary axis with fixed value on input (tied to GND, VCC or using voltage divider) you can force your main axis equal their values to this secondary axis by button press.
You can also use only one physical button implementing two logical button inverted related each other to control described functions of the axis
![image](https://user-images.githubusercontent.com/21309063/149014270-374c9c2a-1c30-49c0-9a11-0354c16a7727.png)

**Comment by wasyl00** [comment]
Fantastic, thanks for your help.
