### ISSUE TITLE
Fake blue pills

### ISSUE THREAD

**Issue by ghost** [vostrenkov/FreeJoy#162]
Hi guys,

First of all, huge thanks for your work, FreeJoy is awesome! :)
Just a quick question rather than an issue: what's your opinion on fake blue pills? I mean some of them I can load your firmware onto, some of them I can't, and honestly I can't tell the difference between fake and genuine chips.
Do you guys know a method by any chance to tell the fake ones apart from the genuine ones?

Many thanks.

**Comment by Reksotiv** [comment]
Hi
I have 3 bluepilles, two of them are fake but work like original. [About fakes](https://github.com/keirf/Greaseweazle/wiki/STM32-Fakes)
And you can check with this application:
[stmTest.zip](https://github.com/FreeJoy-Team/FreeJoy/files/8214079/stmTest.zip)

![image](https://user-images.githubusercontent.com/29454172/157429868-8ebf5176-3c8b-4e6e-93a0-60d804c24692.png)

**Comment by ghost** [comment]
That's great, thank you very much.
I have a few which I can load the fw onto, but the FreeJoyQT does not recognize them, and I have no idea what I'm doing wrong. They are all genuine according to the tester.

**Comment by Reksotiv** [comment]
do you do everything as written here? https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/Flashing-firmware-with-ST-Link-programmer.md
are you flashing the .hex file?
some usb cables are only for charging.

**Comment by ghost** [comment]
Got it fixed, thank you, I got confused with VID numbers :)

Many thanks for your quick help!

**Comment by harrinator-yxz** [comment]
Will anything that says STM32F103C8 work?
