### ISSUE TITLE
Fw 1.7.0.x is incompatible with new QT configurator

### ISSUE THREAD

**Issue by ghost** [vostrenkov/FreeJoy#168]
Hey guys,

Again, huge thanks for your hard work :)
Is there any chance that the 1.7.1.x QT will be compatible with the older firmwares?

Cheers

Andras

**Comment by Reksotiv** [comment]
hi, no chance. why don't you update to 1.7.1?

**Comment by ghost** [comment]
I have, there's no problem with it, in fact, I just found out that I can still load the saved config files onto the new firmware which is brilliant. Many thanks!
